### ISSUE TITLE
Activity Audit Middleware deadlocks

### ISSUE THREAD

**Issue by raymer** [lssinc/voyage-api-dotnet#164]
From Jason Kissinger: "FYI -- we had to disable the ActivityAuditMiddleware for the client because we were getting intermittent deadlocks trying to add audit records which resulted in 500 on those requests."

Look into ways to resolve deadlocks.

**Comment by raymer** [comment]
@aeslinger0 I actually wasn't able to reproduce this. I even installed a load tool to hit the API with tons of simultaneous requests with no luck. Not sure if we should refactor that if we can't reproduce it. Otherwise we don't know if it fixed it or not. Thoughts?

**Comment by aeslinger0** [comment]
@raymer We may never know if we fixed it or not, being that it's intermittent, but we might get lucky. We can reduce the variables at play by bypassing Entity Framework and avoiding the SELECT's altogether. The worst that could happen is that people would still get deadlocks, but they're already getting them today.

**Comment by raymer** [comment]
@aeslinger0 sure sounds good.
