### ISSUE TITLE
Security: Use public/private key for signing JWT token

### ISSUE THREAD

**Issue by maniphanh** [lssinc/voyage-api-dotnet#62]
**Siging JWT**

- Create public/private key if not existing in key store
- Create JWT signing service that provides signing certificate
- Apply signing cert to JWT token generator
- Use public/private key to sign credential when validating JWT on incoming requests

**Comment by raymer** [comment]
@tmichalski This is done but I would like us to revisit this in the future, I'll create a new issue.
